### ISSUE TITLE
Problems found during running the code using nuScenses 1.0-mini

### ISSUE THREAD

**Issue by haodong2000** [Mrmoore98/VectorMapNet_code#25]
Hi developers!

I just want to try the code using v1.0-mini dataet, but after I successfully ran the `nuscenses_convertor.py`, I met with problems while running `python tools/train.py configs/vectormapnet.py`, the log is as below:

```python
Traceback (most recent call last):
  File "D:\Miniconda3\envs\vectormapnet\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "E:\ZJU_Research\EXPLORE\VectorMapNet\plugin\datasets\nusc_dataset.py", line 35, in __init__
    super().__init__(
  File "E:\ZJU_Research\EXPLORE\VectorMapNet\plugin\datasets\base_dataset.py", line 57, in __init__
    self.pipeline = Compose(pipeline)
  File "e:\zju_research\explore\vectormapnet\mmdetection3d\mmdet3d\datasets\pipelines\compose.py", line 31, in __init__
    transform = build_from_cfg(transform, MMDET_PIPELINES)
  File "D:\Miniconda3\envs\vectormapnet\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: VectorizeLocalMap: [Errno 2] No such file or directory: './datasets/nuScenes\\maps\\expansion\\boston-seaport.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 261, in <module>
    main()
  File "tools/train.py", line 224, in main
    datasets = [build_dataset(cfg.data.train)]
  File "e:\zju_research\explore\vectormapnet\mmdetection3d\mmdet3d\datasets\builder.py", line 46, in build_dataset
    dataset = build_from_cfg(cfg, MMDET_DATASETS, default_args)
  File "D:\Miniconda3\envs\vectormapnet\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: NuscDataset: VectorizeLocalMap: [Errno 2] No such file or directory: './datasets/nuScenes\\maps\\expansion\\boston-seaport.json'
```

I found that in `map_transform.py`, you wrote:

```python
        self.MAPS = ['boston-seaport', 'singapore-hollandvillage',
                     'singapore-onenorth', 'singapore-queenstown']
```

and I am wondering whether we can use the v1.0-mini to execute the code and if yes, how to solve the problem? Should I manually download this map files to corrsponding positions?

Thanks!

**Comment by haodong2000** [comment]
Maybe I forgot this:

![image](https://user-images.githubusercontent.com/67775090/218958819-6fe26d67-7493-4e58-8e63-e95c51415462.png)
