### ISSUE TITLE
problems about nuScenes datasets

### ISSUE THREAD

**Issue by longzuyan** [Mrmoore98/VectorMapNet_code#26]
Hi developers!

I just want to try the code using v1.0-mini dataet, but after I successfully ran the _nuscenses_convertor.py_, I met with problems while running _python tools/train.py configs/vectormapnet.py_, the log is as below:

```
collecting samples...
collected 323 samples in 0.01s
Traceback (most recent call last):
  File "/home/long/anaconda3/envs/vechdmap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/long/VectorMapNet_code-mian/plugin/datasets/pipelines/map_transform.py", line 65, in __init__
    self.nusc_maps[loc] = NuScenesMap(
  File "/home/long/anaconda3/envs/vechdmap/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 100, in __init__
    raise Exception('Error: You are using an outdated map version (%s)! '
Exception: Error: You are using an outdated map version (%s)! Please go to https://www.nuscenes.org/download to download the latest map!
```

But i did download the map from the official website. Do you have a better solution?
Thanks!

**Comment by hongxiaoy** [comment]
Maybe you should download the MapExpansion files from nuScenes official website, the updated version is v1.3.

**Comment by longzuyan** [comment]
> Maybe you should download the MapExpansion files from nuScenes official website, the updated version is v1.3.

thanks, i got it.
