### ISSUE TITLE
Can you please provide the config file for using the lidar?

### ISSUE THREAD

**Issue by mohamed-mkh15** [Mrmoore98/VectorMapNet_code#33]
Can you please provide the config file for using the lidar? just modifying the current config file and changing "use_lidar" in "input_modality" to true isn't working

**Comment by Honminden** [comment]
same problem and trying to solve yet, seems lidar points are not loaded
```
Traceback (most recent call last):
  File "/home/saq/lab/VectorMapNet_code/tools/train.py", line 261, in <module>
    main()
  File "/home/saq/lab/VectorMapNet_code/tools/train.py", line 250, in main
    train_model(
  File "/home/saq/lab/VectorMapNet_code/mmdetection3d/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/saq/lab/VectorMapNet_code/plugin/models/mapers/base_mapper.py", line 123, in train_step
    loss, log_vars, num_samples = self(**data_dict)
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saq/lab/VectorMapNet_code/plugin/models/mapers/base_mapper.py", line 91, in forward
    return self.forward_train(*args, **kwargs)
  File "/home/saq/lab/VectorMapNet_code/plugin/models/mapers/vectormapnet.py", line 109, in forward_train
    _bev_feats = self.backbone(img, img_metas=img_metas, points=points)
  File "/home/saq/lab/VectorMapNet_code/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saq/lab/VectorMapNet_code/plugin/models/backbones/ipm_backbone.py", line 230, in forward
    lidar_feat = self.get_lidar_feature(points)
  File "/home/saq/lab/VectorMapNet_code/plugin/models/backbones/ipm_backbone.py", line 286, in get_lidar_feature
    ptensor, pmask = points
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Steplerchik** [comment]
@Mrmoore98 Please, could you share with us how you uploaded lidar data to the model?
